### ISSUE TITLE
CCDirector::sharedDirector()->setNextDeltaTimeZero(true) slow the animation ???

### ISSUE THREAD

**Issue by raymondlu** [raymondlu/super-animation-samples#10]
some guys tole me that CCDirector::sharedDirector()->setNextDeltaTimeZero(true) in SuperAnimNode::PlaySection can slow the animation, don't know why, will check it later. if you have the same problem remove this line.

**Comment by landvibe** [comment]
yes, it slows all animation.
for example,
sprite->runAction(CCSequence::create(CCDelayTime::create(1.0),
                                                         CCCallFunc::create(...
                                                         NULL));
it should call a function after 1 sec, but if we include setNextDeltaTimeZero(true), then it call a function after 2 sec;;;

anyway, is there no problem removing the line?

**Comment by raymondlu** [comment]
no problem to remove it.
