### ISSUE TITLE
I want to use Movieclip.

### ISSUE THREAD

**Issue by singkamuy** [raymondlu/super-animation-samples#11]
Hi.
Are there any plans to support the MovieClip in the future?
Thanks for the great tool!!

**Comment by raymondlu** [comment]
movieclip is a little complicated :-)
right now I don't have plan to support it.
anyway, if you have any question when using this tool, feel free to contact me.

**Comment by singkamuy** [comment]
Hi raymondlu.
Thank you for answers.
I hope to in the future SAC.
