### ISSUE TITLE
loop animation for convenience

### ISSUE THREAD

**Issue by landvibe** [raymondlu/super-animation-samples#12]
sometimes I need loop animation like walking animation.
I currently do like this...
OnAnimSectionEnd(...){
if(theLabelName=="walking") node->playSection("Walking");
}

It will be better to support loop option.
for example,
node->playSection("Walking",true); // the second parameter is isLoop

**Comment by raymondlu** [comment]
suggestion is taken :-)
when I finishing the current new feature, I will add this function.

**Comment by raymondlu** [comment]
it is available in the latest code.

**Comment by landvibe** [comment]
thank you!
