### ISSUE TITLE
Operation in OSX 10.9 Mavericks

### ISSUE THREAD

**Issue by singkamuy** [raymondlu/super-animation-samples#28]
Hi.
I am working on Super Animation Converter version 2.1.
I think xxx.plist so no longer output from the OSX 10.9 Mavericks.
Is there a solution?
Thanks.

**Comment by singkamuy** [comment]
I'm sorry.
Are you generate xxx.plist It was TexturePacker.app.
I was very rude.

**Comment by raymondlu** [comment]
:-)
