### ISSUE TITLE
I want setFlipX or setFlipY.

### ISSUE THREAD

**Issue by landvibe** [raymondlu/super-animation-samples#3]
First of all, i really appreciate your work.

Sprite class support setFlipX and setFlipY.
and i think many people will want functions like those sprite support (ex. setOpacity)
Do you have plan to make those functions?

**Comment by raymondlu** [comment]
set flip x & y have been added in the new version, please check the sample code.

**Comment by raymondlu** [comment]
just fixed a bug for setflipx & setflipy.
please check the latest sample code.

**Comment by landvibe** [comment]
Very good. I appreciate for your work.

I should control the position of superAnimNode.
but when i call setFlipX or setFlipY, the position is changed. (the position of my object is center in flash area)
i think the anchorPoint is (0,0) in your implementation.
could you give me options for it? (in my case, anchorPoint (0.5,0.5))

thanks

**Comment by raymondlu** [comment]
I did fix a bug for anchor point yesterday.
but not sure whether fix the problem you said.

did you use SetFlipX or SetFlipY with the latest code?

**Comment by landvibe** [comment]
it works well with the latest code, good~

**Comment by Basil99998** [comment]
First , Thanks for the development of such a great tool !
can u please provide a link for almost 5 min long animation to download  that support the tool to test the performance !

**Comment by raymondlu** [comment]
I'm sorry.
But I don't quite understand your point.
Do you need animation to test the tool, or something else?
Or you have other problem about this tool?

**Comment by Basil99998** [comment]
Basically i am a programmer
I don't have any problem !
But to know the best performance of the tool , i need to test  2-3 set of animation of very long length(about 2 min long) at a time !
many of the animation i downloaded from the sites not supported by the tool
So can u provide either a very big set of animation sequence that you tested or any sites details for such a big set of animation that supported by the tool

**Comment by raymondlu** [comment]
I see.
But I don't have that kind of animation.
All I have have uploaded to the "flashs" folder.
Maybe you can create one by yourself following the rule in the help doc.
:-)

**Comment by Basil99998** [comment]
ok , one more doubt ! can u implement the same thing in corona ! because corona is best for 2d cross platform  ?

**Comment by raymondlu** [comment]
corona?
maybe I wil do the porting if I have money to buy a licence...
:-)

**Comment by Basil99998** [comment]
Corona have free trial version also ...

**Comment by raymondlu** [comment]
ok, free is good.
will try it later.
:-)
