### ISSUE TITLE
cocos2dx 3.2

### ISSUE THREAD

**Issue by ghost** [raymondlu/super-animation-samples#33]
I want to know if it is working with cocos2dx 3.2, I tried but seems it is working but just doesn't appears on scene.

thanks

**Comment by ghost** [comment]
i worked out how to do that,

SuperAnimNodeV2.h change virtual void draw(...) to
virtual void draw(Renderer *renderer, const Mat4& transform, uint32_t flags) override;

and in cpp
transformUpdated to _transformUpdated

**Comment by ghost** [comment]
It is working completly correct for you? For me the animation is always covered by other sptites

**Comment by raymondlu** [comment]
I've just committed samples for cocos2d-3.2, please have a check.
thank you, @kusamochi

**Comment by ghost** [comment]
@krzysiekk117 sorry for the late reply, at the time I wrote the comment, it worked. What I did was a really simple animation.

@raymondlu Thank you, I hope it works well with the latest version, I will test it out later.
