### ISSUE TITLE
a bug in latest cocos2d-x

### ISSUE THREAD

**Issue by landvibe** [raymondlu/super-animation-samples#4]
Hi, Raymond

in the latest cocos2d-x (version 2.1.1) it seems to do not working.
Every SuperAnimNode is not visible.
i checked working well in previous version.
Could you check this bug?

Thanks.

**Comment by landvibe** [comment]
additional information.
it works well until cocos2d-x 2.0.4
but the bug appears from cocos2d-x 2.1.0

**Comment by raymondlu** [comment]
Hi,
I've uploaded a brand new version to github.Please have a check.:-)

Date: Wed, 20 Feb 2013 22:11:08 -0800
