### ISSUE TITLE
Super Animation Converter

### ISSUE THREAD

**Issue by mateuszjanczewski** [raymondlu/super-animation-samples#40]
Hi Raymond,
do you think it's possible to upload source code of your export here? We're using it in our games and would be really happy to contribute in improving it for future developers.

Best!

**Comment by vkbsb** [comment]
I was going to ask for this as well. This will help me make a.case for this to be integrated into Godot engine as one of the ways to import flash animations.

**Comment by mateuszjanczewski** [comment]
Also it would be awesome to have command line tool, because we want to add this part of our workflow to Jenkins :)
