### ISSUE TITLE
Android Bug about file path

### ISSUE THREAD

**Issue by landvibe** [raymondlu/super-animation-samples#5]
Your code works well on iOS.
But when i try it on Android, it has a bug.

I recommand this code change.

***********************\* before
        FILE *aFile = fopen(aFullPath.c_str(), "rb");
        if (aFile == NULL)
        {
            assert(false && "Can't open animation file.");
            return false;
        }

```
    fseek(aFile, 0, SEEK_END);
    unsigned long aFileSize = ftell(aFile);
    fseek(aFile, 0, SEEK_SET);
    unsigned char *aFileBuffer = new unsigned char[aFileSize];
    if (aFileBuffer == NULL)
    {
        assert(false && "Cannot allocate memory.");
        return false;
    }
    aFileSize = fread(aFileBuffer, sizeof(unsigned char), aFileSize, aFile);
    fclose(aFile);
```

***********************\* after
        unsigned long aFileSize = 0;
        unsigned char\* aFileBuffer = cocos2d::CCFileUtils::sharedFileUtils()->getFileData(aFullPath.c_str(), "rb", &aFileSize);
        BufferReader aBuffer;
        aBuffer.SetData(aFileBuffer, aFileSize);

**Comment by landvibe** [comment]
And there are another function that does not work on Android.
bool hasFile(std::string theFileFullPath)

how about giving user texture management. (i mean...not implement it in your code)
thanks.

**Comment by raymondlu** [comment]
oh, I see.
thank you very much.
I will improve my code as you suggest above later.
:-)

**Comment by landvibe** [comment]
ok, i checked the bug fixed.
