### ISSUE TITLE
Resize issue

### ISSUE THREAD

**Issue by FrancoisDupayrat** [raymondlu/super-animation-samples#6]
I have an issue with resizing on the app: it's impossible to use non-integer value.

If I try to input a number with a dot under 1, I'll have the pop-up which says it only accept values between 0.1 and 10

If I try to input a number with a dot over 1, it will use the integer value of it.

If I try to input a number with a comma (which, in my local language, french, is the separator for real numbers), it will correctly set the label, but when I try to use the resize, it will do the same behavior as above.

Is there a workaround or do you plan to fix that bug ?

**Comment by raymondlu** [comment]
thank you.

I will try to reproduce this bug on my Mac later.
In my code, I use AppKit built-in function to convert string to a float value.
not very sure whether it relates to locale setting.

I don't know whether I am very clear about your issue.
If you input non-integer value, for example  0.75 or 1.50, which is the standard way to represent a float value, 
the converter doesn't work properly?

**Comment by FrancoisDupayrat** [comment]
If I input 0.75, I get the popup about between 0.1 and 10.0. If I input 1.50, it automatically reset to 1.00 when I press enter.

I didn't find the source code of the Converter on the repo, is it available somewhere ? I could try to fix the bug myself if it's open source.

**Comment by raymondlu** [comment]
Here it is a workaround, maybe you can have a try.
Go to System Preferences/Language & Text on your Mac, in the popup dialog, select the Formats tab,
then you can change the Region, maybe you can change to Unites States, or China, then run the converter again.

**Comment by FrancoisDupayrat** [comment]
Thanks, it's working. On Mac OS 10.8.2, the options is under Preferences -> Language & Text -> Region Tab -> Customize Numbers. There I can change the separator from ',' to '.'

**Comment by mrdedalinez** [comment]
why you wold not parse the string to replace ',' to '.' defore convert to a float from string?

**Comment by raymondlu** [comment]
thank you for your suggestion.
in my code, I am using AppKit built-in function to convert string to a float value, which is not under my control.
unfortunately that that function doesn't work properly if your OS language is French.
still don't know why.
yes, I could get the raw string from editor box, and convert it manually by myself to fix this bug.
:-)

**Comment by FrancoisDupayrat** [comment]
From the behavior, I'd say you use the function 2 times : the first time to validate the input when the user press enter : this time works fine and convert the ',' to '.' 
But then, you redo that validation using the converted string when the user click the resize button, which trigger a problem since the '.' isn't good anymore.

A possible solution would be to keep the float value the first time to validate it and use that instead of retrying to validate the string in the box.

**Comment by raymondlu** [comment]
Thank you for your suggestion.
I think I know where goes wrong after reviewing my code.
And I've just uploaded a new binary, could you help me to do a  little test for this issue?

**Comment by FrancoisDupayrat** [comment]
It's working perfectly, thanks. I'm closing the issue.
